### ISSUE TITLE
[activitylog] Log rotation

### ISSUE THREAD

**Issue by H3xadecimal** [calebj/calebj-cogs#16]
Title says it all.

---
- [x] Implement filename-based rotation
  - periods: daily, weekly, monthly, yearly, or disabled
  - filename format is ISO 8601: `YYYYMMDD--PNX_channelid.log`

**Comment by calebj** [comment]
Because of the way logs work, this isn't currently possible. Log events are just dumped into a single, long file for each channel. There are a handful of ways to make it easier to seek through them, one is to generate indexes for files to make it easy to seek to the proper position; another is to generate files per day, week, or whatever time period.
