### ISSUE TITLE
ReDash > Datadog :D

### ISSUE THREAD

**Issue by XxPoNaGeXx** [calebj/calebj-cogs#37]
It would be cool to see the datadog cog be used for this https://redash.io/

It's open source!

**Comment by calebj** [comment]
The datadog cog uses your machine's local statsd instance. Even if you don't actually *use* datadog, as long as your machine's statsd can take the reports from the cog, it shouldn't matter what site you're using.

**Comment by calebj** [comment]
Much, much later, I remember to update this again.

Redash is just a query frontend, it doesn't handle the events themselves. That would be the [StatsD](https://github.com/etsy/statsd) collection agent and a time-series database such as [Graphite](https://github.com/graphite-project) or [Prometheus](https://github.com/prometheus/prometheus). Regular StatsD doesn't have tags or events, which I believe are important for a bot. The cog assumes that DataDog's custom version of StatsD, which supports those things, is running instead.

With regular StatsD, you would be able to track how many servers and channels the bot is in, how many voice players are running, and so on. But you wouldn't you be able to identify which bot sent the stat if you're running more than one, which I am.

If you still want this, you should post a request on the [cog board](https://github.com/Cog-Creators/Cog-Board). It's not a matter of just supporting another backend; a whole new cog would have to be written to work with regular StatsD and [pystatsd](https://github.com/jsocol/pystatsd). I don't think it would be difficult, and I wouldn't mind if someone used this one as a starting point (provided they follow the GPL's terms).

I'm closing this issue, since it can only be resolved with a new cog.
